services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1225
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data