spring:
  application:
    name: Bob-doduk

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Hibernate? DDL ?? ???? ?? (create, update, validate, none ? ??)
      dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL Dialect ?? ??
    show-sql: true                                      # SQL ??? ??? ?? (??? ??)

  sql:
    init:
      mode: always                                      # ?????? ?? ? SQL ????? ?? ??
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==